name: flutter_tooltip
description: Tooltip function built in for flutter. Please press star in my repo if you like it. Thank you.
version: 0.1.0
author: Robby Rahmana <robbyrahmana79@gmail.com>
homepage: https://github.com/robbyrahmana/flutter_tooltip

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_slider_indicator: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
